//
//  Tablas.swift
//  RFC
//
//  Created by Josue Mosiah Contreras Rocha on 9/23/19.
//  Copyright © 2019 Josue Mosiah Contreras Rocha. All rights reserved.
//

import Foundation

struct Tablas {
    let tablaUno: Dictionary<String, String> = [
        " ": "00",
        "0": "00",
        "1": "01",
        "2": "02",
        "3": "03",
        "4": "04",
        "5": "05",
        "6": "06",
        "7": "07",
        "8": "08",
        "9": "09",
        "&": "10", "Ñ": "10",
        "A": "11",
        "B": "12",
        "C": "13",
        "D": "14",
        "E": "15",
        "F": "16",
        "G": "17",
        "H": "18",
        "I": "19",
        "J": "21",
        "K": "22",
        "L": "23",
        "M": "24",
        "N": "25",
        "O": "26",
        "P": "27",
        "Q": "28",
        "R": "29",
        "S": "32",
        "T": "33",
        "U": "34",
        "V": "35",
        "W": "36",
        "X": "37",
        "Y": "38",
        "Z": "39",
        ",": "", ".": ""
    ]
    
    let tablaDos: Dictionary<Int, String> = [
        0: "1",
        1: "2",
        2: "3",
        3: "4",
        4: "5",
        5: "6",
        6: "7",
        7: "8",
        8: "9",
        9: "A",
        10: "B",
        11: "C",
        12: "D",
        13: "E",
        14: "F",
        15: "G",
        16: "H",
        17: "I",
        18: "J",
        19: "K",
        20: "L",
        21: "M",
        22: "N",
        23: "P",
        24: "Q",
        25: "R",
        26: "S",
        27: "T",
        28: "U",
        29: "V",
        30: "W",
        31: "X",
        32: "Y",
        33: "Z"
    ]
    
    let tablaTres: Dictionary<String, Int> = [
        "0": 0,
        "1": 1,
        "2": 2,
        "3": 3,
        "4": 4,
        "5": 5,
        "6": 6,
        "7": 7,
        "8": 8,
        "9": 9,
        "A": 10,
        "B": 11,
        "C": 12,
        "D": 13,
        "E": 14,
        "F": 15,
        "G": 16,
        "H": 17,
        "I": 18,
        "J": 19,
        "K": 20,
        "L": 21,
        "M": 22,
        "N": 23,
        "&": 24, "Ñ": 24,
        "O": 25,
        "P": 26,
        "Q": 27,
        "R": 28,
        "S": 29,
        "T": 30,
        "U": 31,
        "V": 32,
        "W": 33,
        "X": 34,
        "Y": 35,
        "Z": 36,
        " ": 37
    ]
    
    let tablaCuatro: Dictionary<String, String> = [
        "BUEI": "BUEX",
        "CACA": "CACX",
        "CAGA": "CAGX",
        "CAKA": "CAKX",
        "COGE": "COGX",
        "COJE": "COJX",
        "FETO": "FETX",
        "JOTO": "JOTX",
        "KACO": "KACX",
        "KAGO": "KAGX",
        "KOJO": "KOJX",
        "KULO": "KULX",
        "LOCO": "LOCX",
        "MAMO": "MAMX",
        "MEAS": "MEAX",
        "MION": "MIOX",
        "MULA": "MULX",
        "PEDO": "PEDX",
        "PUTA": "PUTX",
        "PUTO": "PUTX",
        "MAME": "MAMX",
        "MEAR": "MEAX",
        "MEON": "MEOX",
        "MOCO": "MOCX",
        "PEDA": "PEDX",
        "PENE": "PENX",
        "CACO": "CACX",
        "CAGO": "CAGX",
        "CAKO": "CAKX",
        "COJA": "COJX",
        "COJI": "COJX",
        "CULO": "CULX",
        "GUEY": "GUEX",
        "KACA": "KACX",
        "KAGA": "KAGX",
        "KOGE": "KOGX",
        "KAKA": "KAKX",
        "LOCA": "LOCX",
        "LOKA": "LOKX",
        "QULO": "QULX",
        "RUIN": "RUIX",
        "RATA": "RATX"
    ]
    
    let tablaCinco: Array<String> = [
        #"\bA. EN P.\b"#, #"\bA.C.\b"#, #"\bAL\b"#, #"\bAND\b"#, #"\bC.D.\b"#, #"\bC.V.\b"#,
        #"\bCIA\b"#, #"\bCOMPANY\b"#, #"\bCOMPAÑIA\b"#, #"\bCON\b"#, #"\bCOOP\b"#, #"\bCOOPERATIVA\b"#,
        #"\bDE\b"#, #"\bDEL\b"#, #"\bE\b"#, #"\bE. EN N.C.\b"#, #"\bEL\b"#, #"\bEN\b"#, #"\bI.A.P.\b"#,
        #"\bLA\b"#, #"\bLAS\b"#, #"\bLOS\b"#, #"\bMAC\b"#, #"\bMC\b"#, #"\bOF\b"#, #"\bPARA\b"#, #"\bPOR\b"#,
        #"\bR.L.\b"#, #"\bS. DE\b"#, #"\bS. EN C.\b"#, #"\bS. EN C. POR A.\b"#, #"\bS.A.\b"#, #"\bS.A. DE\b"#,
        #"\bS.C\b."#, #"\bS.C.L.\b"#, #"\bS.C.S\b"#, #"\bS.N.C.\b"#,  #"\bSOC\b"#, #"\bSOCIEDAD\b"#,
        #"\bSUS\b"#, #"\bTHE\b"#, #"\bVAN\b"#, #"\bVON\b"#, #"\bY\b"#
    ]
    
    let tablaSeis: Array<String> = [
        "D", "DEL", "LA", "LOS", "LAS", "Y", "MC", "MAC", "VON", "VAN"
    ]
}
